name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
inputs:
  path_dockerfile:
    description: "Dockerfile Path"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Dockerfile Path"
    required: true
  tag_name:
    description: "Dockerfile Path"
    required: false
runs:
  using: composite
  steps:
    - run: |
        echo "Update me with the necessary commands"
      shell: bash
